// Furniture catalogue — curated subset of the product's real items.js (authentic
// brands, prices, swatches, ratings). `shape` drives the blocky iso stand-in;
// fw/fd/fh are footprint width, depth and height in feet.
window.CATALOGUE = {
  sofa:      { label:'Sofa', cat:'Seating', sub:'Sofas', brand:'Forma Studio', price:899, priceMax:1299, rating:4.3, reviews:142, shape:'sofa', fw:3, fd:1.4, fh:1.5, color:'#b8997a',
    swatches:[{name:'Charcoal',hex:'#4a4a4a'},{name:'Sand',hex:'#c4a882'},{name:'Navy',hex:'#27405f'},{name:'Sage',hex:'#7f9a7e'}],
    sizes:[{label:'2-Seater',price:699},{label:'3-Seater',price:899},{label:'Sectional',price:1299}],
    materials:'Hardwood frame · woven fabric', desc:'Low-profile sofa with solid hardwood legs and premium woven cushions.' },
  chair:     { label:'Accent Chair', cat:'Seating', sub:'Accent Chairs', brand:'Form & Sit', price:249, priceMax:449, rating:4.6, reviews:88, shape:'chair', fw:1.2, fd:1.2, fh:1.5, color:'#8aa98c',
    swatches:[{name:'Sage',hex:'#7a9e7e'},{name:'Terracotta',hex:'#c4785a'},{name:'Slate',hex:'#6a7a8a'}],
    sizes:[{label:'Accent',price:249},{label:'Armchair',price:449}],
    materials:'Powder-coated steel · bouclé', desc:'A versatile accent chair with memory-foam seat and bouclé cover.' },
  boucle:    { label:'Bouclé Chair', cat:'Seating', sub:'Accent Chairs', brand:'The Cozy Co', price:389, rating:4.8, reviews:204, shape:'chair', fw:1.3, fd:1.3, fh:1.4, color:'#e3d9c7',
    swatches:[{name:'Ivory',hex:'#e8e0d0'},{name:'Caramel',hex:'#c8a060'},{name:'Midnight',hex:'#2a2a3a'}],
    sizes:[{label:'Standard',price:389}],
    materials:'Curved bouclé · oak base', desc:'Pillowy bouclé lounge chair — a reader-favourite cozy corner piece.' },
  ottoman:   { label:'Ottoman', cat:'Seating', sub:'Ottomans', brand:'The Cozy Co', price:149, rating:4.5, reviews:61, shape:'box', fw:1.3, fd:1.3, fh:0.6, color:'#cdbfa6',
    swatches:[{name:'Oat',hex:'#d8ccae'},{name:'Rust',hex:'#b5683f'},{name:'Forest',hex:'#445f47'}],
    sizes:[{label:'Round',price:149},{label:'Storage',price:199}],
    materials:'Foam fill · hidden storage', desc:'A soft footrest with hidden storage inside.' },
  coffee:    { label:'Coffee Table', cat:'Tables', sub:'Coffee Tables', brand:'Knot & Grain', price:329, priceMax:529, rating:4.4, reviews:96, shape:'table', fw:2.2, fd:1.2, fh:0.5, color:'#9c7b53',
    swatches:[{name:'Walnut',hex:'#6b4e32'},{name:'Oak',hex:'#b58e5a'},{name:'White',hex:'#e6e2da'}],
    sizes:[{label:'Round',price:329},{label:'Rectangular',price:429},{label:'Large',price:529}],
    materials:'Solid oak · matte finish', desc:'A grounded centrepiece with a generous lower shelf.' },
  side:      { label:'Side Table', cat:'Tables', sub:'Side Tables', brand:'Knot & Grain', price:129, rating:4.2, reviews:54, shape:'table', fw:1, fd:1, fh:1.4, color:'#a98a5e',
    swatches:[{name:'Oak',hex:'#b58e5a'},{name:'Black',hex:'#2c2c2c'},{name:'Brass',hex:'#b89149'}],
    sizes:[{label:'Petite',price:129},{label:'Tall',price:159}],
    materials:'Oak top · metal legs', desc:'Pull it beside any seat for a lamp, book, or cup.' },
  dining:    { label:'Dining Table', cat:'Tables', sub:'Dining', brand:'Knot & Grain', price:749, priceMax:1149, rating:4.7, reviews:130, shape:'table', fw:3.5, fd:1.8, fh:1.5, color:'#8f6f49',
    swatches:[{name:'Walnut',hex:'#6b4e32'},{name:'Oak',hex:'#b58e5a'},{name:'Ash',hex:'#cabfa8'}],
    sizes:[{label:'Seats 4',price:749},{label:'Seats 6',price:949},{label:'Seats 8',price:1149}],
    materials:'Solid wood · seats 4–8', desc:'A family table built to gather around for years.' },
  desk:      { label:'Desk', cat:'Tables', sub:'Desks', brand:'Worksmith', price:299, priceMax:459, rating:4.5, reviews:78, shape:'table', fw:2.4, fd:1.1, fh:1.5, color:'#9a8163',
    swatches:[{name:'Oak',hex:'#b58e5a'},{name:'White',hex:'#e6e2da'},{name:'Graphite',hex:'#3a3a40'}],
    sizes:[{label:'Compact',price:299},{label:'Standard',price:379},{label:'L-Shape',price:459}],
    materials:'Cable management · oak', desc:'A focused work surface with tidy cable routing.' },
  bookshelf: { label:'Bookshelf', cat:'Storage', sub:'Bookshelves', brand:'Knot & Grain', price:279, priceMax:399, rating:4.4, reviews:112, shape:'tall', fw:2, fd:0.8, fh:5, color:'#947a55',
    swatches:[{name:'Oak',hex:'#b58e5a'},{name:'Walnut',hex:'#6b4e32'},{name:'White',hex:'#e6e2da'}],
    sizes:[{label:'3-Shelf',price:279},{label:'5-Shelf',price:399}],
    materials:'Engineered wood · 5 tiers', desc:'Open shelving for books, plants and objects.' },
  dresser:   { label:'Dresser', cat:'Storage', sub:'Dressers', brand:'Maison Oak', price:549, rating:4.6, reviews:73, shape:'box', fw:2.6, fd:1, fh:2.6, color:'#a4895f',
    swatches:[{name:'Oak',hex:'#b58e5a'},{name:'Sage',hex:'#7f9a7e'},{name:'Navy',hex:'#27405f'}],
    sizes:[{label:'6-Drawer',price:549},{label:'9-Drawer',price:749}],
    materials:'Soft-close drawers', desc:'Roomy storage with a calm, low silhouette.' },
  bed:       { label:'Bed Frame', cat:'Bedroom', sub:'Beds', brand:'Maison Oak', price:649, priceMax:949, rating:4.7, reviews:188, shape:'bed', fw:5, fd:6.5, fh:1.2, color:'#b59f86',
    swatches:[{name:'Linen',hex:'#d8ccba'},{name:'Slate',hex:'#5a6473'},{name:'Blush',hex:'#d8a6a6'}],
    sizes:[{label:'Full',price:649},{label:'Queen',price:799},{label:'King',price:949}],
    materials:'Upholstered · wood slats', desc:'An upholstered platform bed with a soft headboard.' },
  nightstand:{ label:'Nightstand', cat:'Bedroom', sub:'Nightstands', brand:'Maison Oak', price:139, rating:4.3, reviews:64, shape:'box', fw:1, fd:0.9, fh:1.4, color:'#a98a5e',
    swatches:[{name:'Oak',hex:'#b58e5a'},{name:'White',hex:'#e6e2da'},{name:'Black',hex:'#2c2c2c'}],
    sizes:[{label:'1-Drawer',price:139},{label:'2-Drawer',price:179}],
    materials:'Oak · soft-close', desc:'A bedside companion with a handy drawer.' },
  floorlamp: { label:'Floor Lamp', cat:'Lighting', sub:'Floor Lamps', brand:'Lumen & Co', price:189, rating:4.5, reviews:97, shape:'lamp', fw:0.9, fd:0.9, fh:5, color:'#d8c9a8',
    swatches:[{name:'Linen',hex:'#e3d8bd'},{name:'Black',hex:'#2c2c2c'},{name:'Brass',hex:'#b89149'}],
    sizes:[{label:'Arc',price:189},{label:'Tripod',price:219}],
    materials:'Linen shade · dimmable', desc:'Soft ambient light with a warm linen shade.' },
  tablelamp: { label:'Table Lamp', cat:'Lighting', sub:'Table Lamps', brand:'Lumen & Co', price:89, rating:4.6, reviews:140, shape:'lamp', fw:0.7, fd:0.7, fh:1.6, color:'#e0d2b2',
    swatches:[{name:'Cream',hex:'#ece0c6'},{name:'Sage',hex:'#7f9a7e'},{name:'Clay',hex:'#bd7d5c'}],
    sizes:[{label:'Standard',price:89}],
    materials:'Ceramic base · linen', desc:'A bedside glow with a hand-thrown ceramic base.' },
  pendant:   { label:'Pendant Light', cat:'Lighting', sub:'Ceiling', brand:'Lumen & Co', price:159, rating:4.4, reviews:58, shape:'pendant', fw:1.1, fd:1.1, fh:1, color:'#c9b88c',
    swatches:[{name:'Rattan',hex:'#caa86e'},{name:'Black',hex:'#2c2c2c'},{name:'White',hex:'#e6e2da'}],
    sizes:[{label:'Single',price:159},{label:'Cluster',price:289}],
    materials:'Woven rattan shade', desc:'A woven pendant that casts a dappled glow.' },
  rug:       { label:'Area Rug', cat:'Textiles', sub:'Rugs', brand:'Loom & Field', price:199, priceMax:349, rating:4.5, reviews:166, shape:'flat', fw:4, fd:3, fh:0.06, color:'#c9b59a',
    swatches:[{name:'Oatmeal',hex:'#d6c6ac'},{name:'Rust',hex:'#b5683f'},{name:'Indigo',hex:'#3a4a6b'},{name:'Moss',hex:'#76854f'}],
    sizes:[{label:"5×7'",price:199},{label:"8×10'",price:349}],
    materials:'Hand-loomed wool', desc:'A grounding wool rug that anchors the whole room.' },
  plant:     { label:'Potted Plant', cat:'Decor', sub:'Plants', brand:'Sproutling', price:69, rating:4.8, reviews:233, shape:'plant', fw:1, fd:1, fh:2.6, color:'#5e8a55',
    swatches:[{name:'Terracotta',hex:'#bd7d5c'},{name:'White',hex:'#e6e2da'},{name:'Charcoal',hex:'#3a3a40'}],
    sizes:[{label:'Medium',price:69},{label:'Tall',price:99}],
    materials:'Faux fiddle-leaf · pot', desc:'A low-fuss leafy corner that never needs water.' },
  vase:      { label:'Vase', cat:'Decor', sub:'Vases', brand:'Sproutling', price:34, rating:4.4, reviews:41, shape:'box', fw:0.5, fd:0.5, fh:1, color:'#cfa98a',
    swatches:[{name:'Clay',hex:'#c08a64'},{name:'Sage',hex:'#7f9a7e'},{name:'Cream',hex:'#ece0c6'}],
    sizes:[{label:'Tall',price:34},{label:'Bud',price:22}],
    materials:'Glazed stoneware', desc:'A sculptural vase, lovely empty or full.' },
  mirror:    { label:'Floor Mirror', cat:'Wall Decor', sub:'Mirrors', brand:'Maison Oak', price:179, rating:4.6, reviews:84, shape:'tall', fw:1.6, fd:0.4, fh:5, color:'#b9c4cc',
    swatches:[{name:'Oak',hex:'#b58e5a'},{name:'Black',hex:'#2c2c2c'},{name:'Brass',hex:'#b89149'}],
    sizes:[{label:'Arched',price:179},{label:'Rectangular',price:159}],
    materials:'Arched · leaning', desc:'A full-length leaning mirror that opens up the room.' },
  tvstand:   { label:'TV Stand', cat:'Storage', sub:'Media', brand:'Knot & Grain', price:329, rating:4.3, reviews:71, shape:'box', fw:3.4, fd:1, fh:1.3, color:'#9c7b53',
    swatches:[{name:'Walnut',hex:'#6b4e32'},{name:'Oak',hex:'#b58e5a'},{name:'White',hex:'#e6e2da'}],
    sizes:[{label:'Standard',price:329},{label:'Wide',price:429}],
    materials:'Cable cut-outs · oak', desc:'A low media console with tidy storage.' },
  bench:     { label:'Bench', cat:'Seating', sub:'Benches', brand:'Form & Sit', price:189, rating:4.4, reviews:49, shape:'box', fw:3, fd:0.9, fh:1, color:'#b89a76',
    swatches:[{name:'Oak',hex:'#b58e5a'},{name:'Linen',hex:'#d8ccba'},{name:'Black',hex:'#2c2c2c'}],
    sizes:[{label:'Bedroom',price:189},{label:'Entry',price:159}],
    materials:'Upholstered top · wood', desc:'A versatile bench for the foot of a bed or entry.' },
  barcart:   { label:'Bar Cart', cat:'Specialty', sub:'Entertaining', brand:'Lumen & Co', price:219, rating:4.5, reviews:60, shape:'table', fw:2, fd:1, fh:2.6, color:'#b89149',
    swatches:[{name:'Brass',hex:'#b89149'},{name:'Black',hex:'#2c2c2c'},{name:'Chrome',hex:'#c4c8cc'}],
    sizes:[{label:'2-Tier',price:219}],
    materials:'Brass frame · glass', desc:'A rolling bar cart for hosting in style.' },
};
window.CAT_ORDER = ['Seating','Tables','Storage','Bedroom','Lighting','Textiles','Decor','Wall Decor','Specialty'];
window.CATALOGUE_KEYS = Object.keys(window.CATALOGUE);

// Style panel presets
window.WALL_PRESETS = [
  { name:'Cloud',     hex:'#ece7f5' }, { name:'Blush',  hex:'#f0d8d8' },
  { name:'Sage',      hex:'#cdd8c4' }, { name:'Sky',     hex:'#cfe0ee' },
  { name:'Butter',    hex:'#f2e6c2' }, { name:'Clay',    hex:'#e0c2ad' },
  { name:'Charcoal',  hex:'#3a3a44' }, { name:'Plum',    hex:'#5a3f63' },
];
window.FLOOR_PRESETS = [
  { name:'Oak',     hex:'#c8a878', tex:'wood'  }, { name:'Walnut', hex:'#7c5a3c', tex:'wood' },
  { name:'Ash',     hex:'#d8cdb8', tex:'wood'  }, { name:'Carpet', hex:'#c4b9ad', tex:'soft' },
  { name:'Tile',    hex:'#d2d8dc', tex:'tile'  }, { name:'Concrete',hex:'#b0b0b4', tex:'flat' },
  { name:'Terracotta',hex:'#bd7d5c', tex:'tile'}, { name:'Slate',  hex:'#5a6068', tex:'tile' },
];
