// Export floor plan as downloadable image (PNG) or printable page
// Uses the same canvas drawing logic as FloorPlanPage

export function exportFloorPlanPNG(cells, internalWalls, gridW, gridD, roomZones, roomZoneLabels, items) {
  const CELL = 16
  const PAD = 40
  const W = gridW * CELL + PAD * 2
  const H = gridD * CELL + PAD * 2

  const canvas = document.createElement('canvas')
  canvas.width = W * 2; canvas.height = H * 2
  const ctx = canvas.getContext('2d')
  ctx.scale(2, 2)

  // White background for print
  ctx.fillStyle = '#ffffff'
  ctx.fillRect(0, 0, W, H)

  // Title
  ctx.fillStyle = '#333333'
  ctx.font = 'bold 14px Outfit, sans-serif'
  ctx.fillText('DaydreamDwelling — Floor Plan', PAD, 20)
  ctx.font = '10px Outfit, sans-serif'
  ctx.fillStyle = '#888888'
  ctx.fillText(`${gridW}×${gridD} ft · ${cells.size} sq ft · ${roomZones?.length ?? 0} rooms`, PAD, 34)

  // Cells
  for (const key of cells) {
    const [c, r] = key.split(',').map(Number)
    ctx.fillStyle = '#f0f0f0'
    ctx.fillRect(PAD + c * CELL, PAD + r * CELL, CELL - 0.5, CELL - 0.5)
  }

  // Room zone fills + labels
  const COLORS = ['#dce8f8', '#f8e8d0', '#d8f0d8', '#f0d8e8', '#e8e0d0', '#d0e8f0', '#f0f0d0', '#e0d8f0']
  roomZones?.forEach((zone, i) => {
    ctx.fillStyle = COLORS[i % COLORS.length]
    for (const key of zone.cells) {
      const [c, r] = key.split(',').map(Number)
      ctx.fillRect(PAD + c * CELL, PAD + r * CELL, CELL - 0.5, CELL - 0.5)
    }
    // Label
    let sumC = 0, sumR = 0
    for (const key of zone.cells) { const [c, r] = key.split(',').map(Number); sumC += c; sumR += r }
    const cx = PAD + (sumC / zone.cells.size + 0.5) * CELL
    const cy = PAD + (sumR / zone.cells.size + 0.5) * CELL
    const label = roomZoneLabels?.[`zone_${zone.id}`] ?? `Room ${i + 1}`
    ctx.fillStyle = '#333333'
    ctx.font = `bold ${Math.max(8, CELL * 0.6)}px Outfit, sans-serif`
    ctx.textAlign = 'center'
    ctx.fillText(label, cx, cy)
    ctx.font = `${Math.max(7, CELL * 0.5)}px Outfit, sans-serif`
    ctx.fillStyle = '#888888'
    ctx.fillText(`${zone.cells.size} sq ft`, cx, cy + CELL * 0.7)
  })

  // Boundary walls
  ctx.strokeStyle = '#333333'
  ctx.lineWidth = 2
  ctx.lineCap = 'round'
  for (const key of cells) {
    const [c, r] = key.split(',').map(Number)
    const x = PAD + c * CELL, y = PAD + r * CELL
    if (!cells.has(`${c},${r-1}`)) { ctx.beginPath(); ctx.moveTo(x, y); ctx.lineTo(x + CELL, y); ctx.stroke() }
    if (!cells.has(`${c},${r+1}`)) { ctx.beginPath(); ctx.moveTo(x, y + CELL); ctx.lineTo(x + CELL, y + CELL); ctx.stroke() }
    if (!cells.has(`${c-1},${r}`)) { ctx.beginPath(); ctx.moveTo(x, y); ctx.lineTo(x, y + CELL); ctx.stroke() }
    if (!cells.has(`${c+1},${r}`)) { ctx.beginPath(); ctx.moveTo(x + CELL, y); ctx.lineTo(x + CELL, y + CELL); ctx.stroke() }
  }

  // Internal walls
  ctx.strokeStyle = '#666666'
  ctx.lineWidth = 1.5
  for (const edgeKey of (internalWalls ?? [])) {
    const sep = edgeKey.lastIndexOf(':')
    const [c, r] = edgeKey.slice(0, sep).split(',').map(Number)
    const dir = edgeKey.slice(sep + 1)
    const x = PAD + c * CELL, y = PAD + r * CELL
    ctx.beginPath()
    if (dir === 'N') { ctx.moveTo(x, y); ctx.lineTo(x + CELL, y) }
    if (dir === 'S') { ctx.moveTo(x, y + CELL); ctx.lineTo(x + CELL, y + CELL) }
    if (dir === 'W') { ctx.moveTo(x, y); ctx.lineTo(x, y + CELL) }
    if (dir === 'E') { ctx.moveTo(x + CELL, y); ctx.lineTo(x + CELL, y + CELL) }
    ctx.stroke()
  }

  // Stairs
  for (const it of (items ?? [])) {
    if (!it.stairs || it.returnStair) continue
    const sw = it.stairW ?? 3, sd = it.stairD ?? 5
    const rot = it.rotation === 90 || it.rotation === 270
    const ew = rot ? sd : sw, ed = rot ? sw : sd
    const x = PAD + it.col * CELL, y = PAD + it.row * CELL
    ctx.fillStyle = '#e8dcc8'
    ctx.fillRect(x, y, ew * CELL, ed * CELL)
    ctx.strokeStyle = '#b0956a'
    ctx.lineWidth = 1
    ctx.strokeRect(x, y, ew * CELL, ed * CELL)
    ctx.fillStyle = '#b0956a'
    ctx.font = `${Math.max(7, CELL * 0.5)}px Outfit, sans-serif`
    ctx.textAlign = 'center'
    ctx.fillText('Stairs', x + ew * CELL / 2, y + ed * CELL / 2 + 3)
  }

  // Footer
  ctx.textAlign = 'left'
  ctx.fillStyle = '#aaaaaa'
  ctx.font = '8px Outfit, sans-serif'
  ctx.fillText('Generated by DaydreamDwelling.com', PAD, H - 10)
  ctx.fillText(new Date().toLocaleDateString(), W - PAD - 60, H - 10)

  // Download
  const link = document.createElement('a')
  link.download = 'floorplan.png'
  link.href = canvas.toDataURL('image/png')
  link.click()
}
